[project]
name = "web-crawler"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "bs4>=0.0.2",
    "requests>=2.32.4",
]
